# Moonraker Configuration File

################################################

[include moonraker.my.config.conf]

################################################

[server]
host: 0.0.0.0
port: 7125
# Make sure the klippy_uds_address is correct.  It is initialized
# to the default address.
klippy_uds_address: /tmp/uds

[machine]
provider: none
validate_service: false
validate_config: false

[file_manager]
file_system_observer: none

[authorization]
enable_api_key: false
trusted_clients:
  0.0.0.0/0
